'''initial_migration

Revision ID: 9e9bca2d2425
Revises:
Create Date: 2022-03-05 17:37:07.621238

'''

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '9e9bca2d2425'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'user_model',
        sa.Column(
            'created',
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text('CURRENT_TIMESTAMP'),
            nullable=False,
        ),
        sa.Column(
            'updated',
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text('CURRENT_TIMESTAMP'),
            nullable=False,
        ),
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('email', sa.String(), nullable=False),
        sa.Column('email_verified_dt', sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column('nickname', sa.String(), nullable=True),
        sa.Column('password', sa.String(), nullable=True),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_user_model')),
        sa.UniqueConstraint('email', name=op.f('uq_df9611602afc57819460c930e80d5eda')),
    )
    op.create_table(
        'user_follow_relation',
        sa.Column(
            'created',
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text('CURRENT_TIMESTAMP'),
            nullable=False,
        ),
        sa.Column(
            'updated',
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text('CURRENT_TIMESTAMP'),
            nullable=False,
        ),
        sa.Column('request_user_id', sa.Integer(), nullable=False),
        sa.Column('target_user_id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ['request_user_id'],
            ['user_model.id'],
            name=op.f('fk_93dbc565605c5f4fa5f1a07f26e4cf26'),
        ),
        sa.PrimaryKeyConstraint(
            'request_user_id', 'target_user_id', name=op.f('pk_user_follow_relation')
        ),
    )
    op.create_index(
        op.f('ix_93dbc565605c5f4fa5f1a07f26e4cf26'),
        'user_follow_relation',
        ['request_user_id'],
        unique=False,
    )
    op.create_table(
        'user_oauth_relation',
        sa.Column(
            'created',
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text('CURRENT_TIMESTAMP'),
            nullable=False,
        ),
        sa.Column(
            'updated',
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text('CURRENT_TIMESTAMP'),
            nullable=False,
        ),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('uid', sa.String(), nullable=False),
        sa.Column('provider_type', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ['user_id'],
            ['user_model.id'],
            name=op.f('fk_46a4058838f15d869d2af3e12bf6afae'),
        ),
        sa.PrimaryKeyConstraint('user_id', 'uid', name=op.f('pk_user_oauth_relation')),
        sa.UniqueConstraint(
            'uid', 'provider_type', name=op.f('uq_0df791716f6e56aca5c843b20d2716c5')
        ),
    )
    op.create_index(
        op.f('ix_46a4058838f15d869d2af3e12bf6afae'),
        'user_oauth_relation',
        ['user_id'],
        unique=False,
    )
    op.create_table(
        'user_profile_image_log_model',
        sa.Column(
            'created',
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text('CURRENT_TIMESTAMP'),
            nullable=False,
        ),
        sa.Column(
            'updated',
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text('CURRENT_TIMESTAMP'),
            nullable=False,
        ),
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('profile_image_url', sa.String(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ['user_id'],
            ['user_model.id'],
            name=op.f('fk_6ae828da741253c7b1033c58bdf37b94'),
        ),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_user_profile_image_log_model')),
    )
    op.create_index(
        op.f('ix_6ae828da741253c7b1033c58bdf37b94'),
        'user_profile_image_log_model',
        ['user_id'],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f('ix_6ae828da741253c7b1033c58bdf37b94'),
        table_name='user_profile_image_log_model',
    )
    op.drop_table('user_profile_image_log_model')
    op.drop_index(
        op.f('ix_46a4058838f15d869d2af3e12bf6afae'), table_name='user_oauth_relation'
    )
    op.drop_table('user_oauth_relation')
    op.drop_index(
        op.f('ix_93dbc565605c5f4fa5f1a07f26e4cf26'), table_name='user_follow_relation'
    )
    op.drop_table('user_follow_relation')
    op.drop_table('user_model')
    # ### end Alembic commands ###
