"""init

Revision ID: c97014438f91
Revises: 
Create Date: 2022-05-16 01:05:58.344383

"""

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = "c97014438f91"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "album",
        sa.Column(
            "created",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column(
            "updated",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column("spotify_id", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("release_date", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("total_tracks", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("spotify_id", name=op.f("pk_album")),
    )
    op.create_index(
        op.f("ix_afad70a85634588783d79e5f33eab9ac"), "album", ["name"], unique=False
    )
    op.create_table(
        "artist",
        sa.Column(
            "created",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column(
            "updated",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column("spotify_id", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("spotify_id", name=op.f("pk_artist")),
    )
    op.create_table(
        "digging_tag",
        sa.Column(
            "created",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column(
            "updated",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("icon", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("name", name=op.f("pk_digging_tag")),
    )
    op.create_table(
        "user",
        sa.Column(
            "created",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column(
            "updated",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("email", sa.String(), nullable=True),
        sa.Column("email_verified_dt", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("nickname", sa.String(), nullable=True),
        sa.Column("password", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_user")),
        sa.UniqueConstraint("email", name=op.f("uq_74cda3621ed4527e9f4d082372d5ab7c")),
    )
    op.create_table(
        "image",
        sa.Column(
            "created",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column(
            "updated",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column("album_id", sa.String(), nullable=False),
        sa.Column("width", sa.Integer(), nullable=False),
        sa.Column("height", sa.Integer(), nullable=False),
        sa.Column("url", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["album_id"],
            ["album.spotify_id"],
            name=op.f("fk_f12c4869fef85710923a8cb58a54d07b"),
        ),
        sa.PrimaryKeyConstraint("album_id", name=op.f("pk_image")),
    )
    op.create_table(
        "track",
        sa.Column(
            "created",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column(
            "updated",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column("spotify_id", sa.String(), nullable=False),
        sa.Column("album_id", sa.String(), nullable=True),
        sa.Column("duration_ms", sa.Float(), nullable=False),
        sa.Column("track_number", sa.Integer(), nullable=False),
        sa.Column("preview_url", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["album_id"],
            ["album.spotify_id"],
            name=op.f("fk_abe49e7e44a25c16a955c18a170ab51f"),
        ),
        sa.PrimaryKeyConstraint("spotify_id", name=op.f("pk_track")),
    )
    op.create_table(
        "user_follow",
        sa.Column(
            "created",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column(
            "updated",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column("request_user_id", sa.Integer(), nullable=False),
        sa.Column("target_user_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["request_user_id"],
            ["user.id"],
            name=op.f("fk_e06bb250ca07500fb4d9c989b8e2953c"),
        ),
        sa.ForeignKeyConstraint(
            ["target_user_id"],
            ["user.id"],
            name=op.f("fk_a9b8783bf0b3502099524316044fd688"),
        ),
        sa.PrimaryKeyConstraint(
            "request_user_id", "target_user_id", name=op.f("pk_user_follow")
        ),
    )
    op.create_index(
        op.f("ix_e06bb250ca07500fb4d9c989b8e2953c"),
        "user_follow",
        ["request_user_id"],
        unique=False,
    )
    op.create_table(
        "user_oauth_login",
        sa.Column(
            "created",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column(
            "updated",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("uid", sa.String(), nullable=False),
        sa.Column("provider_type", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"], ["user.id"], name=op.f("fk_e0f60ad8696657e88f7a223585863bc5")
        ),
        sa.PrimaryKeyConstraint("user_id", "uid", name=op.f("pk_user_oauth_login")),
        sa.UniqueConstraint(
            "uid", "provider_type", name=op.f("uq_a5ac8655450a55e2aa899f27c87c1274")
        ),
    )
    op.create_index(
        op.f("ix_e0f60ad8696657e88f7a223585863bc5"),
        "user_oauth_login",
        ["user_id"],
        unique=False,
    )
    op.create_table(
        "user_profile_image_log",
        sa.Column(
            "created",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column(
            "updated",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("profile_image_url", sa.String(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"], ["user.id"], name=op.f("fk_0e29871c98645bae809dd23c27164210")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_user_profile_image_log")),
    )
    op.create_index(
        op.f("ix_0e29871c98645bae809dd23c27164210"),
        "user_profile_image_log",
        ["user_id"],
        unique=False,
    )
    op.create_table(
        "artist_track",
        sa.Column(
            "created",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column(
            "updated",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column("artist_id", sa.String(), nullable=False),
        sa.Column("track_id", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["artist_id"],
            ["artist.spotify_id"],
            name=op.f("fk_a364f6b42a4359d1b3d3ce399c9728b1"),
        ),
        sa.ForeignKeyConstraint(
            ["track_id"],
            ["track.spotify_id"],
            name=op.f("fk_1e47ce68941c516c91646fcf9580b9de"),
        ),
        sa.PrimaryKeyConstraint("artist_id", "track_id", name=op.f("pk_artist_track")),
    )
    op.create_index(
        op.f("ix_1e47ce68941c516c91646fcf9580b9de"),
        "artist_track",
        ["track_id"],
        unique=False,
    )
    op.create_table(
        "digging_log",
        sa.Column(
            "created",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column(
            "updated",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("track_id", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["track_id"],
            ["track.spotify_id"],
            name=op.f("fk_e9fc7095f22459cbaa0ce4ce99405991"),
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["user.id"], name=op.f("fk_2dd6e14278aa5d75837b2ff4511a1909")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_digging_log")),
    )
    op.create_table(
        "digging_log_tag",
        sa.Column(
            "created",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column(
            "updated",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column("digging_log_id", sa.Integer(), nullable=False),
        sa.Column("tag_name", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["digging_log_id"],
            ["digging_log.id"],
            name=op.f("fk_67fde6a7ba235d8b8d7523e7799294a6"),
        ),
        sa.ForeignKeyConstraint(
            ["tag_name"],
            ["digging_tag.name"],
            name=op.f("fk_aa7b1fa9cc1f5dc4aa39dce1865ac9b4"),
        ),
        sa.PrimaryKeyConstraint(
            "digging_log_id", "tag_name", name=op.f("pk_digging_log_tag")
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("digging_log_tag")
    op.drop_table("digging_log")
    op.drop_index(
        op.f("ix_1e47ce68941c516c91646fcf9580b9de"), table_name="artist_track"
    )
    op.drop_table("artist_track")
    op.drop_index(
        op.f("ix_0e29871c98645bae809dd23c27164210"), table_name="user_profile_image_log"
    )
    op.drop_table("user_profile_image_log")
    op.drop_index(
        op.f("ix_e0f60ad8696657e88f7a223585863bc5"), table_name="user_oauth_login"
    )
    op.drop_table("user_oauth_login")
    op.drop_index(op.f("ix_e06bb250ca07500fb4d9c989b8e2953c"), table_name="user_follow")
    op.drop_table("user_follow")
    op.drop_table("track")
    op.drop_table("image")
    op.drop_table("user")
    op.drop_table("digging_tag")
    op.drop_table("artist")
    op.drop_index(op.f("ix_afad70a85634588783d79e5f33eab9ac"), table_name="album")
    op.drop_table("album")
    # ### end Alembic commands ###
